spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.25.21.167:3306/identifiers?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: videoweb
    password: suntek
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 600000

mybatis:
  type-aliases-package: com.example.springwebredis.web.model
  mapper-locations: classpath:com/example/springwebredis/web/mapper/*Mapper.xml
  configuration:
#    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    cache-enabled: true
