jetcache:
  statIntervalMinutes: 0
  areaInCacheName: false
  local:
    default:
      type: caffeine
      limit: 1000
      expireAfterWriteInMillis: 100000
  remote:
    default:
      type: redis
      host: 127.0.0.1
      port: 6379
      password: 123456
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50