server:
  servlet:
    context-path: /
  tomcat:
    max-connections: 8192
    threads:
      max: 200


spring:
  profiles:
    active: dev
  flyway:
    table: flyway_schema_history
    baselineOnMigrate: true